name = "jj"
default_agent = "reaper_agent"

[[agents]]
  name = "reaper_agent"
  model = "gpt-4.1-nano"
  plugins = ["reaper_project_manager", "reascript_launcher"]

[[agents]]
  name = "example_agent"
  model = "gpt-4.1-nano"
  plugins = ["mytool", "weather", "calculator"]

[[agents]]
  name = "test"
  model = "gpt-4.1-nano"

[[agents]]
  name = "hiji"
  model = "gpt-4.1-nano"

[[agents]]
  name = "ㅁㄴㅇ"
  model = "gpt-4.1-nano"
