name           = "jj"
default_agent  = "reaper_agent"

[[agents]]
name       = "reaper_agent"
model      = "gpt-4.1-nano"
tool_path  = [
  "./plugins/reaper_project_manager/reaper_project_manager.so",
]

[[agents]]
name       = "example_agent"
model      = "gpt-4.1-nano"
tool_path  = [
  "./plugins/mytool.so",
  "./plugins/weather.so",
  "./plugins/calculator.so",
]
